/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Reparation;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ReparationService;

/**
 *
 * @author X1 YOGA
 */
public class FiltrageTypeForm extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiltrageForm
     */
    private ReparationService rs;
    private DefaultTableModel model = null;

    public FiltrageTypeForm() {
        initComponents();
        rs = new ReparationService();
        model = new DefaultTableModel(
                new String[]{"Id_reparation", "Immatricule", "Type", "Cout", "Date"},
                0
        );
        tableReparations.setModel(model);
        chargerToutesLesReparations();

    }

    private void chargerToutesLesReparations() {
        model.setRowCount(0);
        List<Reparation> reparations = rs.findAll();
        for (Reparation r : reparations) {
            model.addRow(new Object[]{
                r.getId_reparation(),
                r.getImmatricule(),
                r.getType(),
                r.getCout(),
                r.getDate()
            });
        }
    }

    private void filtrerParType() {
        String type = typetxt.getText().trim();

        if (type.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Veuillez entrer un type",
                    "Erreur",
                    JOptionPane.WARNING_MESSAGE);
            chargerToutesLesReparations();
            return;
        }

        model.setRowCount(0);
        List<Reparation> reparations = rs.findByType(type);

        if (reparations.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Aucune réparation trouvée pour le type : " + type,
                    "Résultat",
                    JOptionPane.INFORMATION_MESSAGE);
            chargerToutesLesReparations();
            return;
        }

        for (Reparation r : reparations) {
            model.addRow(new Object[]{
                r.getId_reparation(),
                r.getImmatricule(),
                r.getType(),
                r.getCout(),
                r.getDate()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        typetxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReparations = new javax.swing.JTable();
        btnFiltrer = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Fitage");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2), "Options de Filtrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Type : ");

        tableReparations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_reparation", "Type", "Cout", "Date", "Immatricule"
            }
        ));
        tableReparations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReparationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReparations);

        btnFiltrer.setBackground(new java.awt.Color(102, 204, 255));
        btnFiltrer.setText("Filtrer");
        btnFiltrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(94, 94, 94)
                .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(70, 70, 70)
                .addComponent(btnFiltrer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(409, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(typetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrer))
                .addContainerGap(651, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(73, 73, 73)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 603, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(17, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableReparationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReparationsMouseClicked
        int row = tableReparations.getSelectedRow();
        if (row >= 0) {
            Object typeObj = model.getValueAt(row, 2);
            typetxt.setText(typeObj != null ? typeObj.toString() : "");

        }
    }//GEN-LAST:event_tableReparationsMouseClicked

    private void btnFiltrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerActionPerformed
        filtrerParType();
    }//GEN-LAST:event_btnFiltrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReparations;
    private javax.swing.JTextField typetxt;
    // End of variables declaration//GEN-END:variables
}
