/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Vehicule;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.VehiculeService;

/**
 *
 * @author X1 YOGA
 */
public class FiltrageMarque extends javax.swing.JInternalFrame {
    private VehiculeService vs;       
    private DefaultTableModel model;
    /**
     * Creates new form FiltrageMarque
     */
    public FiltrageMarque() {
        initComponents();
        vs = new VehiculeService();
        model = new DefaultTableModel(
            new String[]{"Immatricule","Marque", "Modele"},
            0
        );
        listevehicule.setModel(model);
        chargerTousVehicules();       
    }
    private void chargerTousVehicules() {
        model.setRowCount(0);
        List<Vehicule> list = vs.findAll();
        for (Vehicule r : list) {
            model.addRow(new Object[]{
                    r.getImmatricule(),
                    r.getMarque(),
                    r.getModele()
            });
        }
    }
   private void filtrerParMarque() {
        String marque = marquetxt.getText().trim();
        if (marque.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez entrer une marque", "Erreur", JOptionPane.WARNING_MESSAGE);
            return;
        }
        model.setRowCount(0);
        List<Vehicule> list = vs.findByMarque(marque);
        
        if (list.isEmpty()) {
            JOptionPane.showMessageDialog(this, 
                    "Aucun véhicule trouvé pour la marque: " + marque, 
                    "Résultat", 
                    JOptionPane.INFORMATION_MESSAGE);
        chargerTousVehicules();       
            return;
        }

        for (Vehicule v : list) {
            model.addRow(new Object[]{
                v.getImmatricule(),
                v.getMarque(),
                v.getModele()
            });
        }
   }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        marquetxt = new javax.swing.JTextField();
        btnFiltrer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        listevehicule = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Filtrage par Marque");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 2), "Options de Filtrage", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jLabel1.setText("Marque");

        btnFiltrer.setBackground(new java.awt.Color(102, 204, 255));
        btnFiltrer.setText("Filtrere");
        btnFiltrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrerActionPerformed(evt);
            }
        });

        listevehicule.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        listevehicule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Immatricule", "Marque", "Modele"
            }
        ));
        listevehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listevehiculeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listevehicule);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(marquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(86, 86, 86)
                        .addComponent(btnFiltrer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 545, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(marquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltrer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listevehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listevehiculeMouseClicked
        int row = listevehicule.getSelectedRow();
        if (row >= 0) {
            String marque = (String) model.getValueAt(row, 1);
            marquetxt.setText(marque);
        }
    }//GEN-LAST:event_listevehiculeMouseClicked

    private void btnFiltrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrerActionPerformed
         filtrerParMarque();
     }//GEN-LAST:event_btnFiltrerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFiltrer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listevehicule;
    private javax.swing.JTextField marquetxt;
    // End of variables declaration//GEN-END:variables
}
