/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import javax.swing.JDesktopPane;
import javax.swing.JFrame;
import services.ClientService;

/**
 *
 * @author X1 YOGA
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        ClientMenuItem = new javax.swing.JMenuItem();
        VehiculeMenuItem = new javax.swing.JMenuItem();
        reapartionMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        statistiqueMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        FtirageTypeMenuItem = new javax.swing.JMenuItem();
        FiltrageMarqueMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuBar.setBackground(new java.awt.Color(204, 204, 204));
        menuBar.setAutoscrolls(true);

        fileMenu.setMnemonic('f');
        fileMenu.setText("Gestion");

        ClientMenuItem.setMnemonic('o');
        ClientMenuItem.setText("Client");
        ClientMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(ClientMenuItem);

        VehiculeMenuItem.setMnemonic('s');
        VehiculeMenuItem.setText("Vehicule");
        VehiculeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VehiculeMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(VehiculeMenuItem);

        reapartionMenuItem.setMnemonic('a');
        reapartionMenuItem.setText("Reparation");
        reapartionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reapartionMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(reapartionMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Statistique  ");

        statistiqueMenuItem.setMnemonic('t');
        statistiqueMenuItem.setText(" statistique");
        statistiqueMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statistiqueMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(statistiqueMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Filtrage");

        FtirageTypeMenuItem.setMnemonic('c');
        FtirageTypeMenuItem.setText("Filtrage par type");
        FtirageTypeMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FtirageTypeMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(FtirageTypeMenuItem);

        FiltrageMarqueMenuItem.setMnemonic('a');
        FiltrageMarqueMenuItem.setText("Filtrage par marque");
        FiltrageMarqueMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrageMarqueMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(FiltrageMarqueMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1688, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ClientMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientMenuItemActionPerformed
         ClientForm  cf = new ClientForm();
         desktopPane.add(cf);
         cf.setVisible(true);
    }//GEN-LAST:event_ClientMenuItemActionPerformed

    private void VehiculeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VehiculeMenuItemActionPerformed
        VehiculeForm  vf =new VehiculeForm();
        desktopPane.add(vf);
        vf.setVisible(true);
    }//GEN-LAST:event_VehiculeMenuItemActionPerformed

    private void reapartionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reapartionMenuItemActionPerformed
        ReparationForm rf=new ReparationForm();
        desktopPane.add(rf);
        rf.setVisible(true);
    }//GEN-LAST:event_reapartionMenuItemActionPerformed

    private void statistiqueMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statistiqueMenuItemActionPerformed
        StatistiquesForm statsForm = new StatistiquesForm();
        desktopPane.add(statsForm); 
        statsForm.setVisible(true);
    }//GEN-LAST:event_statistiqueMenuItemActionPerformed

    private void FtirageTypeMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FtirageTypeMenuItemActionPerformed
         FiltrageTypeForm ft=new FiltrageTypeForm();
         desktopPane.add(ft);
         ft.setVisible(true);
    }//GEN-LAST:event_FtirageTypeMenuItemActionPerformed

    private void FiltrageMarqueMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrageMarqueMenuItemActionPerformed
        FiltrageMarque fm=new FiltrageMarque();
        desktopPane.add(fm);
        fm.setVisible(true);
    }//GEN-LAST:event_FiltrageMarqueMenuItemActionPerformed

    /**
     * @param args the command line arguments

*/
    public static void main(String args[]) {
           java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
         
        JFrame frame = new JFrame("Connexion");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        JDesktopPane desktop = new JDesktopPane();
        frame.setContentPane(desktop);
        frame.setSize(700, 800);
        frame.setLocationRelativeTo(null);

       LoginForm loginInternal = new LoginForm();
       desktop.add(loginInternal);
       loginInternal.setSize(800, 900);
        loginInternal.setVisible(true);

        frame.setVisible(true);
    }});
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem ClientMenuItem;
    private javax.swing.JMenuItem FiltrageMarqueMenuItem;
    private javax.swing.JMenuItem FtirageTypeMenuItem;
    private javax.swing.JMenuItem VehiculeMenuItem;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem reapartionMenuItem;
    private javax.swing.JMenuItem statistiqueMenuItem;
    // End of variables declaration//GEN-END:variables

}
