package ui;

import entities.Reparation;
import entities.Vehicule;
import java.util.Date;
import java.util.List;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.*;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author X1 YOGA
 */
public class ReparationForm extends javax.swing.JInternalFrame {

    private ReparationService rs = null;
    private VehiculeService vs = null;
    DefaultTableModel model = null;

    /**
     * Creates new form ReparationForm
     */
    public ReparationForm() {
        initComponents();
        vs = new VehiculeService();
        rs = new ReparationService();
        loadReparations();
        loadImmatricules();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public void vider() {
        txtType.setText("");
        txtCout.setText("");
        dateChooser.setDate(null);
        if (cmbImmatricule.getItemCount() > 0) {
            cmbImmatricule.setSelectedIndex(0);
        }
        tableReparations.clearSelection();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtType = new javax.swing.JTextField();
        txtCout = new javax.swing.JTextField();
        dateChooser = new com.toedter.calendar.JDateChooser();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        cmbImmatricule = new javax.swing.JComboBox();
        btnHistorique = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReparations = new javax.swing.JTable();

        setBackground(new java.awt.Color(204, 204, 204));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des reaparation");
        setAutoscrolls(true);
        setDoubleBuffered(true);
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1500, 1000));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 255), 3), "Information Reparation", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 24), new java.awt.Color(153, 0, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(153, 0, 255));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel2.setText("Type   :  ");

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel3.setText("Cout  (DH)  :  ");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel4.setText("Date    :   ");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 22)); // NOI18N
        jLabel5.setText("Immatricule  : ");

        txtType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTypeActionPerformed(evt);
            }
        });

        btnAdd.setBackground(new java.awt.Color(51, 255, 51));
        btnAdd.setText("Ajouter");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(new java.awt.Color(255, 255, 0));
        btnUpdate.setText("Modifier");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setText("Supprimer");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        cmbImmatricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbImmatriculeActionPerformed(evt);
            }
        });

        btnHistorique.setBackground(new java.awt.Color(51, 204, 255));
        btnHistorique.setText("Historique");
        btnHistorique.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 204, 204)));
        btnHistorique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoriqueActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(559, 559, 559)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(btnHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(109, 109, 109))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(128, 128, 128)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCout)
                            .addComponent(txtType)
                            .addComponent(dateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
                            .addComponent(cmbImmatricule, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtType, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbImmatricule, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDelete)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(btnHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
        );

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));

        tableReparations.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id_reparation", "Type", "Cout", "Date", "Immatricule"
            }
        ));
        tableReparations.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReparationsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReparations);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1703, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void loadImmatricules() {
        try {
            cmbImmatricule.removeAllItems();
            List<Vehicule> list = vs.findAll();

            for (Vehicule v : list) {
                cmbImmatricule.addItem(v.getImmatricule());
            }
        } catch (Exception e) {
            // Gestion d'erreur
        }
    }

    private void loadReparations() {
        DefaultTableModel model = (DefaultTableModel) tableReparations.getModel();
        model.setRowCount(0); // Vider la table

        try {
            List<Reparation> list = rs.findAll();

            for (Reparation r : list) {
                model.addRow(new Object[]{
                    r.getId_reparation(),
                    r.getType(),
                    r.getCout(),
                    r.getDate(),
                    r.getImmatricule()
                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur lors du chargement des réparations : " + e.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }
    private void txtTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTypeActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // Validation des champs
        if (txtType.getText().trim().isEmpty()
                || txtCout.getText().trim().isEmpty()
                || dateChooser.getDate() == null
                || cmbImmatricule.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !",
                    "Champs manquants", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String type = txtType.getText().trim();
            double cout = Double.parseDouble(txtCout.getText().trim());
            Date date = dateChooser.getDate();
            String immatricule = cmbImmatricule.getSelectedItem().toString();

            if (cout <= 0) {
                JOptionPane.showMessageDialog(this, "Le coût doit être supérieur à 0 !",
                        "Erreur de validation", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Reparation r = new Reparation(type, cout, date, immatricule);

            if (rs.create(r)) {
                JOptionPane.showMessageDialog(this, "Réparation ajoutée avec succès !",
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                vider();
                loadReparations();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de l'ajout de la réparation !",
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Le coût doit être un nombre valide !",
                    "Erreur de format", JOptionPane.ERROR_MESSAGE);
            txtCout.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        int row = tableReparations.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une réparation à modifier !",
                    "Aucune sélection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (txtType.getText().trim().isEmpty()
                || txtCout.getText().trim().isEmpty()
                || dateChooser.getDate() == null
                || cmbImmatricule.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !",
                    "Champs manquants", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int id = (int) tableReparations.getValueAt(row, 0);

            String type = txtType.getText().trim();
            double cout = Double.parseDouble(txtCout.getText().trim());
            Date date = dateChooser.getDate();
            String immatricule = cmbImmatricule.getSelectedItem().toString();

            if (cout <= 0) {
                JOptionPane.showMessageDialog(this, "Le coût doit être supérieur à 0 !",
                        "Erreur de validation", JOptionPane.ERROR_MESSAGE);
                return;
            }

            Reparation r = new Reparation(id, immatricule, date, type, cout);

            if (rs.update(r)) {
                JOptionPane.showMessageDialog(this, "Réparation modifiée avec succès !",
                        "Succès", JOptionPane.INFORMATION_MESSAGE);
                vider();
                loadReparations();
            } else {
                JOptionPane.showMessageDialog(this, "Erreur lors de la modification !",
                        "Erreur", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Le coût doit être un nombre valide !",
                    "Erreur de format", JOptionPane.ERROR_MESSAGE);
            txtCout.requestFocus();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(),
                    "Erreur", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int row = tableReparations.getSelectedRow();

        if (row == -1) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner une réparation à supprimer !",
                    "Aucune sélection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String type = tableReparations.getValueAt(row, 1).toString();
        String immatricule = tableReparations.getValueAt(row, 4).toString();

        int confirm = JOptionPane.showConfirmDialog(this,
                "Êtes-vous sûr de vouloir supprimer cette réparation ?\n\n"
                + "Type: " + type + "\n"
                + "Immatricule: " + immatricule,
                "Confirmation de suppression",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.WARNING_MESSAGE);

        if (confirm == JOptionPane.YES_OPTION) {
            try {
                int id = (int) tableReparations.getValueAt(row, 0);

                Reparation r = rs.findById(id);

                if (r != null && rs.delete(r)) {
                    JOptionPane.showMessageDialog(this, "Réparation supprimée avec succès !",
                            "Succès", JOptionPane.INFORMATION_MESSAGE);
                    vider();
                    loadReparations();
                } else {
                    JOptionPane.showMessageDialog(this, "Erreur lors de la suppression !",
                            "Erreur", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur : " + e.getMessage(),
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void cmbImmatriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbImmatriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbImmatriculeActionPerformed

    private void tableReparationsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReparationsMouseClicked
        int row = tableReparations.getSelectedRow();

        if (row != -1) {
            try {
                txtType.setText(tableReparations.getValueAt(row, 1).toString());
                txtCout.setText(tableReparations.getValueAt(row, 2).toString());

                Object dateObj = tableReparations.getValueAt(row, 3);
                if (dateObj instanceof Date) {
                    dateChooser.setDate((Date) dateObj);
                }

                String immat = tableReparations.getValueAt(row, 4).toString();
                cmbImmatricule.setSelectedItem(immat);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erreur lors du chargement des données : " + e.getMessage(),
                        "Erreur", JOptionPane.ERROR_MESSAGE);
                e.printStackTrace();
            }
        }
       }//GEN-LAST:event_tableReparationsMouseClicked

    private void btnHistoriqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoriqueActionPerformed
        if(cmbImmatricule.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this,
                "Veuillez sélectionner un véhicule !",
                "Aucune sélection",
                JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            String immatricule = cmbImmatricule.getSelectedItem().toString();
            List<Reparation> reparations = rs.findByVehicule(immatricule);

            if(reparations.isEmpty()) {
                JOptionPane.showMessageDialog(this,
                    "Aucune réparation trouvée pour le véhicule : " + immatricule,
                    "Aucun résultat",
                    JOptionPane.INFORMATION_MESSAGE);
                return;
            }

            JDialog dialogHistorique = new JDialog();
            dialogHistorique.setTitle("Historique - " + immatricule);
            dialogHistorique.setModal(true);
            dialogHistorique.setSize(800, 500);
            dialogHistorique.setLocationRelativeTo(this);
            dialogHistorique.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

            String[] colonnes = {"ID", "Type", "Coût (MAD)", "Date"};
            DefaultTableModel modelHistorique = new DefaultTableModel(colonnes, 0) {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };

            JTable tableHistorique = new JTable(modelHistorique);
            tableHistorique.setFont(new java.awt.Font("Segoe UI", 0, 14));
            tableHistorique.setRowHeight(25);
            tableHistorique.getTableHeader().setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14));

            double coutTotal = 0;
            for(Reparation r : reparations) {
                modelHistorique.addRow(new Object[]{
                    r.getId_reparation(),
                    r.getType(),
                    String.format("%.2f", r.getCout()),
                    r.getDate()
                });
                coutTotal += r.getCout();
            }

            JPanel panelPrincipal = new JPanel(new java.awt.BorderLayout(10, 10));
            panelPrincipal.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

            JScrollPane scrollPane = new JScrollPane(tableHistorique);
            panelPrincipal.add(scrollPane, java.awt.BorderLayout.CENTER);

            JPanel panelTotal = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
            panelTotal.setBackground(new java.awt.Color(255, 255, 255));

            JLabel lblTotal = new JLabel("Total des coûts : " + String.format("%.2f", coutTotal) + " MAD");
            lblTotal.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 18));
            lblTotal.setForeground(new java.awt.Color(255, 0, 0));
            panelTotal.add(lblTotal);

            panelPrincipal.add(panelTotal, java.awt.BorderLayout.SOUTH);

            JPanel panelHaut = new JPanel(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT));
            JButton btnFermer = new JButton("✕");
            btnFermer.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 20));
            btnFermer.setFocusPainted(false);
            btnFermer.setBorderPainted(false);
            btnFermer.setContentAreaFilled(false);
            btnFermer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            btnFermer.addActionListener(e -> dialogHistorique.dispose());
            panelHaut.add(btnFermer);

            panelPrincipal.add(panelHaut, java.awt.BorderLayout.NORTH);

            dialogHistorique.add(panelPrincipal);
            dialogHistorique.setVisible(true);

        } catch(Exception e) {
            JOptionPane.showMessageDialog(this,
                "Erreur lors du chargement de l'historique : " + e.getMessage(),
                "Erreur",
                JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnHistoriqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnHistorique;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cmbImmatricule;
    private com.toedter.calendar.JDateChooser dateChooser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableReparations;
    private javax.swing.JTextField txtCout;
    private javax.swing.JTextField txtType;
    // End of variables declaration//GEN-END:variables
}
