
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import entities.Client;
import entities.Vehicule;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import services.ClientService;
import services.VehiculeService;

/**
 *
 * @author X1 YOGA
 */
public class VehiculeForm extends javax.swing.JInternalFrame {

    VehiculeService vs = null;
    ClientService cs = null;
    DefaultTableModel model = null;
     private String immatricule;

    /**
     * Creates new form VehiculeForm
     */
    public VehiculeForm() {
        initComponents();
        this.setTitle("Gestion des véhicules");
        vs = new VehiculeService();
        cs = new ClientService();
        model = (DefaultTableModel) listevehicule.getModel();
        loadClient();
        load();
    }
    
     private void loadClient() {
        clients.removeAllItems();
        for (Client c : cs.findAll()) {
            clients.addItem(c);
        }
    }

     public void load() {
        model.setRowCount(0);
        for (Vehicule v : vs.findAll()) {
             Client client = cs.findById(v.getIdClient());
             String clientNom = (client != null) ? client.getNom() + " " + client.getPrenom() : "N/A";
            model.addRow(new Object[]{
                v.getImmatricule(),
                v.getMarque(),
                v.getModele(),
                v.getIdClient(), 
                clientNom  
            });
        }
    }
      public void vider() {
        immatriculetxt.setText("");
        marquetxt.setText("");
        modeletxt.setText("");
        if(clients.getItemCount() > 0) {
            clients.setSelectedIndex(0);
        }
        immatricule = null;
        immatriculetxt.setEnabled(true);
    }

    private int getSelectedClientId() {
        Object selectedItem = clients.getSelectedItem();
        if (selectedItem instanceof Client) {
            return ((Client) selectedItem).getId_client();
        }
        return 0; 
    }
    private void selectClientInCombo(int clientId) {
        for (int i = 0; i < clients.getItemCount(); i++) {
            Object item = clients.getItemAt(i);
            if (item instanceof Client) {
                Client client = (Client) item;
                if (client.getId_client() == clientId) {
                    clients.setSelectedItem(client);
                    return;
                }
            }
            if(clients.getItemCount() > 0) {
            clients.setSelectedIndex(0);
        }
        }
   
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        marquetxt = new javax.swing.JTextField();
        modeletxt = new javax.swing.JTextField();
        immatriculetxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        clients = new javax.swing.JComboBox();
        AddVehicule = new javax.swing.JButton();
        UpdateVehicule = new javax.swing.JButton();
        DeleteVehicule = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listevehicule = new javax.swing.JTable();

        setBackground(new java.awt.Color(102, 102, 102));
        setBorder(new javax.swing.border.MatteBorder(null));
        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Gestion des vehicules");
        setAutoscrolls(true);
        setDoubleBuffered(true);
        setFocusTraversalPolicyProvider(true);
        setInheritsPopupMenu(true);
        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1500, 1070));
        try {
            setSelected(true);
        } catch (java.beans.PropertyVetoException e1) {
            e1.printStackTrace();
        }
        setVisible(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 0), 2), "information sur les vehicules", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tw Cen MT Condensed", 1, 24), new java.awt.Color(255, 102, 0))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.setToolTipText("Informations sur les vehicules");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabel1.setText("Marque : ");

        jLabel2.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel2.setText("Modele  : ");

        jLabel3.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel3.setText("Immatricule : ");

        modeletxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modeletxtActionPerformed(evt);
            }
        });

        immatriculetxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                immatriculetxtActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tw Cen MT Condensed", 1, 24)); // NOI18N
        jLabel4.setText("Client :      ");

        clients.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientsActionPerformed(evt);
            }
        });

        AddVehicule.setBackground(new java.awt.Color(51, 255, 51));
        AddVehicule.setText("Ajouter");
        AddVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddVehiculeActionPerformed(evt);
            }
        });

        UpdateVehicule.setBackground(new java.awt.Color(255, 255, 51));
        UpdateVehicule.setText("Modifier");
        UpdateVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateVehiculeActionPerformed(evt);
            }
        });

        DeleteVehicule.setBackground(new java.awt.Color(255, 0, 51));
        DeleteVehicule.setText("Supprimer");
        DeleteVehicule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteVehiculeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(581, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddVehicule, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(modeletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(immatriculetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(UpdateVehicule, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(95, 95, 95)
                        .addComponent(DeleteVehicule)))
                .addContainerGap(502, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(marquetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modeletxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(immatriculetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(clients, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdateVehicule)
                    .addComponent(AddVehicule)
                    .addComponent(DeleteVehicule))
                .addGap(612, 612, 612))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        listevehicule.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 102, 102), null));
        listevehicule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Immatricule", "Marque", "Modele"
            }
        ));
        listevehicule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listevehiculeMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listevehicule);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(805, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void modeletxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modeletxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modeletxtActionPerformed

    private void immatriculetxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_immatriculetxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_immatriculetxtActionPerformed

    private void DeleteVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteVehiculeActionPerformed
             if(immatricule == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un véhicule !");
            return;
        }
        
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment supprimer ce véhicule ?");
        if(reponse == 0) {
            vs.delete(vs.findById(immatricule));
            load();
            vider();
        }
        }//GEN-LAST:event_DeleteVehiculeActionPerformed

    private void AddVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddVehiculeActionPerformed
     if(immatriculetxt.getText().trim().isEmpty() || 
           marquetxt.getText().trim().isEmpty() || 
           modeletxt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs !");
            return;
        }
        
        if(clients.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un client !");
            return;
        }
        
        String immatricule = immatriculetxt.getText().trim();
        String marque = marquetxt.getText().trim();
        String modele = modeletxt.getText().trim();
        int idClient = getSelectedClientId();
        
        vs.create(new Vehicule(immatricule, marque, modele, idClient));
        load();
        vider();
    }//GEN-LAST:event_AddVehiculeActionPerformed

    private void listevehiculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listevehiculeMouseClicked
       int row = listevehicule.getSelectedRow();
        if(row >= 0) {
            immatricule = model.getValueAt(row, 0).toString();
            marquetxt.setText(model.getValueAt(row, 1).toString());
            modeletxt.setText(model.getValueAt(row, 2).toString());
            immatriculetxt.setText(immatricule);
            
            // Récupérer et sélectionner le client
            Object idClientObj = model.getValueAt(row, 3);
            if(idClientObj != null) {
                try {
                    int idClient = Integer.parseInt(idClientObj.toString());
                    selectClientInCombo(idClient);
                } catch(NumberFormatException e) {
                    if(clients.getItemCount() > 0) {
                        clients.setSelectedIndex(0);
                    }
                }
            }
            
            // Désactiver l'immatricule en mode modification
            immatriculetxt.setEnabled(false);
        }
    }//GEN-LAST:event_listevehiculeMouseClicked

    private void UpdateVehiculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateVehiculeActionPerformed
        if(immatricule == null) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner un véhicule !");
            return;
        }
        
        int reponse = JOptionPane.showConfirmDialog(this, "Voulez-vous vraiment modifier ce véhicule ?");
        if(reponse == 0) {
            String marque = marquetxt.getText().trim();
            String modele = modeletxt.getText().trim();
            int idClient = getSelectedClientId();
            
            vs.update(new Vehicule(immatricule, marque, modele, idClient));
            load();
            vider();
        }
    }//GEN-LAST:event_UpdateVehiculeActionPerformed

    private void clientsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddVehicule;
    private javax.swing.JButton DeleteVehicule;
    private javax.swing.JButton UpdateVehicule;
    private javax.swing.JComboBox clients;
    private javax.swing.JTextField immatriculetxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable listevehicule;
    private javax.swing.JTextField marquetxt;
    private javax.swing.JTextField modeletxt;
    // End of variables declaration//GEN-END:variables
}
